import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {CodexKernel} from '../packages/agent/codex-kernel.mjs';
test('only explicit reasoning summary is exposed and tool stages update',async()=>{const k=new CodexKernel({home:fs.mkdtempSync(path.join(os.tmpdir(),'zora-summary-'))});k.active.set('t',{messages:[],toolTrace:[]});k.activities.set('t',{conversationId:'c'});await k.receive({method:'item/reasoning/textDelta',params:{threadId:'t',itemId:'r',delta:'hidden'}});assert.equal(k.activities.get('t').reasoningSummary,undefined);await k.receive({method:'item/reasoning/summaryTextDelta',params:{threadId:'t',itemId:'r',summaryIndex:0,delta:'Summary'}});await k.receive({method:'item/started',params:{threadId:'t',item:{id:'cmd',type:'commandExecution'}}});assert.equal(k.activities.get('t').tools.cmd.status,'running');await k.receive({method:'item/completed',params:{threadId:'t',item:{id:'cmd',type:'commandExecution',status:'completed'}}});assert.equal(k.activities.get('t').tools.cmd.status,'completed');assert.deepEqual(Object.values(k.activities.get('t').reasoningSummary),['Summary']);});
test('retry errors are redacted, retained across restart and cleared as active state after recovery',async()=>{
 const home=fs.mkdtempSync(path.join(os.tmpdir(),'zora-retry-'));const k=new CodexKernel({home,key:'secret-test-key'});k.active.set('t',{messages:[],toolTrace:[]});k.activities.set('t',{threadId:'t',conversationId:'c',status:'running'});
 await k.receive({method:'error',params:{threadId:'t',willRetry:true,error:{message:'stream disconnected secret-test-key',additionalDetails:'Bearer another-secret'}}});const a=k.activities.get('t');assert.equal(a.retrying,true);assert.equal(a.status,'running');assert.equal(a.errors.length,1);assert(!JSON.stringify(a).includes('secret-test-key'));assert(!JSON.stringify(a).includes('another-secret'));
 const restored=new CodexKernel({home});assert.equal(restored.listActivities()[0].errors.length,1);
 await k.receive({method:'item/agentMessage/delta',params:{threadId:'t',delta:'Recovered'}});assert.equal(a.retrying,false);assert.equal(a.errors.length,1);
 await k.receive({method:'error',params:{threadId:'t',willRetry:false,error:{message:'retry exhausted'}}});assert.equal(a.retrying,false);assert.equal(a.error,'retry exhausted');await k.close();
});
test('interrupt targets all owned threads, defers starting turns and blocks later children',async()=>{const k=new CodexKernel({home:fs.mkdtempSync(path.join(os.tmpdir(),'zora-stop-'))});const calls=[];k.request=async(method,p)=>calls.push({method,...p});k.active.set('main',{conversationId:'c',turnId:'turn-main'});k.active.set('child',{conversationId:'c',turnId:'turn-child'});k.active.set('starting',{conversationId:'c'});k.active.set('other',{conversationId:'other',turnId:'other-turn'});assert.equal((await k.interrupt('c')).requested,3);assert.deepEqual(calls.map(x=>x.threadId).sort(),['child','main']);assert.equal(k.active.get('starting').stopRequested,true);assert.equal(k.active.get('other').stopRequested,undefined);await assert.rejects(k.run('child',{ownerConversationId:'c'}),/已停止/);});
