const settings=document.getElementById('settings'),studio=document.getElementById('studio');
if(settings&&studio){
 const row=document.createElement('div');row.className='setting-row';row.innerHTML='<div><h3>工作台壁纸</h3><p>选择本地图片或视频，仅保存在本机。减少动态效果时暂停壁纸视频。</p><small role="status"></small></div><div><button type="button" data-choose>选择壁纸</button> <button type="button" data-reset>恢复默认</button><input type="file" accept="image/*,video/*" hidden></div>';settings.prepend(row);
 const input=row.querySelector('input'),status=row.querySelector('small'),original=studio.querySelector('.studio-backdrop');let custom,url,revision=0;
 const db=new Promise((resolve,reject)=>{const req=indexedDB.open('zora-appearance',1);req.onupgradeneeded=()=>req.result.createObjectStore('settings');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
 async function store(value){const conn=await db;await new Promise((resolve,reject)=>{const tx=conn.transaction('settings','readwrite');tx.objectStore('settings').put(value,'wallpaper');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
 const system=matchMedia('(prefers-reduced-motion: reduce)');const reduced=()=>system.matches||document.documentElement.classList.contains('reduce-motion');
 function sync(){document.querySelectorAll('video.backdrop').forEach(v=>{const page=v.closest('.page');if(reduced()||document.hidden||page?.hidden||v===original&&custom)v.pause();else v.play().catch(()=>{});});}
 function apply(file){custom?.remove();custom=null;if(url){URL.revokeObjectURL(url);url=null;}if(file){url=URL.createObjectURL(file);custom=document.createElement(file.type.startsWith('video/')?'video':'img');custom.className='backdrop studio-backdrop custom-wallpaper';custom.setAttribute('aria-hidden','true');if(custom.tagName==='VIDEO'){custom.muted=true;custom.loop=true;custom.playsInline=true;custom.preload='metadata';custom.addEventListener('loadeddata',sync);}custom.src=url;studio.prepend(custom);original.style.display='none';}else original.style.display='';sync();}
 row.querySelector('[data-choose]').onclick=()=>input.click();input.onchange=async()=>{const file=input.files[0];if(!file)return;if(!/^(image|video)\//.test(file.type)){status.textContent='请选择图片或视频';return;}revision++;try{await store(file);apply(file);status.textContent='已保存壁纸：'+file.name;}catch{status.textContent='本机存储失败，壁纸未更改；请检查可用空间。';}input.value='';};
 row.querySelector('[data-reset]').onclick=async()=>{revision++;try{await store(null);apply(null);status.textContent='已恢复默认壁纸';}catch{status.textContent='保存失败，请重试';}};
 const initial=revision;db.then(conn=>{const req=conn.transaction('settings').objectStore('settings').get('wallpaper');req.onsuccess=()=>{if(revision===initial&&req.result)apply(req.result);};}).catch(()=>status.textContent='壁纸存储不可用');
 new MutationObserver(sync).observe(document.documentElement,{attributes:true,attributeFilter:['class']});document.querySelectorAll('.page').forEach(p=>new MutationObserver(sync).observe(p,{attributes:true,attributeFilter:['hidden']}));system.addEventListener('change',sync);document.addEventListener('visibilitychange',sync);document.addEventListener('play',e=>{if(e.target.matches?.('video.backdrop')&&(reduced()||document.hidden))e.target.pause();},true);sync();
}
