/** Capability catalog driven by 多元探索 docs model matrices. */

const GROK_RATIOS = ['16:9', '9:16', '2:3', '3:2', '1:1'];
const GROK_SIZES = ['720P', '1080P'];
const GROK_MODES = [
  { id: 't2v', name: '文生视频', enabled: true },
  { id: 'i2v', name: '首帧生视频', enabled: true },
  { id: 'fl', name: '首尾帧', enabled: true },
  { id: 'ref', name: '全能参考', enabled: true },
];

const IMAGE_RATIOS_STD = ['1:1', '4:3', '3:2', '2:3', '16:9', '9:16'];
const IMAGE_MODES = [
  { id: 't2i', name: '文生图', enabled: true },
  { id: 'i2i', name: '图生图', enabled: true },
];

/** @type {import('../../apps/server/types.js').ModelCap[]} */
export const MODELS = [

  // —— Agent / 文本 ——
  // 分类依据：多元探索「文本模型支持矩阵」
  // - Chat Completions：适用「聊天、Agent」，支持工具调用
  // - Responses：更适合结构化输出 / 工具编排（Agent 优先入口）
  // - flash / lite / auto 等轻量模型标为普通对话，仍可在 Agent 模式下选用但会注明
  // 仅收录当前 Key 在 GET /v1/models 中可见的文本模型（排除 image/video）

  {
    id: 'gpt-6-astra',
    name: 'GPT 6 Astra',
    kind: 'agent',
    textRole: 'agent',
    family: 'openai-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gpt-5.6-terra',
    name: 'GPT 5.6 Terra',
    kind: 'agent',
    textRole: 'agent',
    family: 'openai-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gpt-5.6-sol',
    name: 'GPT 5.6 Sol',
    kind: 'agent',
    textRole: 'agent',
    family: 'openai-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gpt-5.6-luna',
    name: 'GPT 5.6 Luna',
    kind: 'agent',
    textRole: 'agent',
    family: 'openai-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gpt-5.5',
    name: 'GPT 5.5',
    kind: 'agent',
    textRole: 'agent',
    family: 'openai-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    kind: 'agent',
    textRole: 'agent',
    family: 'claude-text',
    enabled: true,
    route: '/v1/chat/completions',
    nativeRoute: '/v1/messages',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    kind: 'agent',
    textRole: 'agent',
    family: 'claude-text',
    enabled: true,
    route: '/v1/chat/completions',
    nativeRoute: '/v1/messages',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    kind: 'agent',
    textRole: 'agent',
    family: 'claude-text',
    enabled: true,
    route: '/v1/chat/completions',
    nativeRoute: '/v1/messages',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'claude-sonnet-5',
    name: 'Claude Sonnet 5',
    kind: 'agent',
    textRole: 'agent',
    family: 'claude-text',
    enabled: true,
    route: '/v1/chat/completions',
    nativeRoute: '/v1/messages',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    kind: 'agent',
    textRole: 'agent',
    family: 'claude-text',
    enabled: true,
    route: '/v1/chat/completions',
    nativeRoute: '/v1/messages',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro',
    kind: 'agent',
    textRole: 'agent',
    family: 'gemini-text',
    enabled: true,
    route: '/v1/chat/completions',
    nativeRoute: '/v1beta/models/{model}:generateContent',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gemini-3-pro-preview',
    name: 'Gemini 3 Pro',
    kind: 'agent',
    textRole: 'agent',
    family: 'gemini-text',
    enabled: true,
    route: '/v1/chat/completions',
    nativeRoute: '/v1beta/models/{model}:generateContent',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    kind: 'agent',
    textRole: 'agent',
    family: 'deepseek-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'qwen3.7-plus',
    name: 'Qwen 3.7 Plus',
    kind: 'agent',
    textRole: 'agent',
    family: 'qwen-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'qwen3.6-plus',
    name: 'Qwen 3.6 Plus',
    kind: 'agent',
    textRole: 'agent',
    family: 'qwen-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    kind: 'agent',
    textRole: 'agent',
    family: 'moonshot-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'kimi-k2.7-code',
    name: 'Kimi K2.7 Code',
    kind: 'agent',
    textRole: 'agent',
    family: 'moonshot-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'grok-4.6',
    name: 'Grok 4.6',
    kind: 'agent',
    textRole: 'agent',
    family: 'grok-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'grok-4.5',
    name: 'Grok 4.5',
    kind: 'agent',
    textRole: 'agent',
    family: 'grok-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'grok-4-2',
    name: 'Grok 4.2',
    kind: 'agent',
    textRole: 'agent',
    family: 'grok-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'grok-4',
    name: 'Grok 4',
    kind: 'agent',
    textRole: 'agent',
    family: 'grok-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'grok-4-1-expert',
    name: 'Grok 4.1 Expert',
    kind: 'agent',
    textRole: 'agent',
    family: 'grok-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'MiniMax-M3',
    name: 'MiniMax M3',
    kind: 'agent',
    textRole: 'agent',
    family: 'minimax-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'glm-5.3',
    name: 'GLM 5.3',
    kind: 'agent',
    textRole: 'agent',
    family: 'glm-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'glm-5.2',
    name: 'GLM 5.2',
    kind: 'agent',
    textRole: 'agent',
    family: 'glm-text',
    enabled: true,
    route: '/v1/responses',
    fallbackRoute: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'agent', name: 'Agent 任务', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },

  // —— 普通对话（轻量 / Flash；矩阵仍走 Chat Completions，但不作 Agent 首选）——
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    kind: 'agent',
    textRole: 'chat',
    family: 'deepseek-text',
    enabled: true,
    route: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'chat', name: '普通对话', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    kind: 'agent',
    textRole: 'chat',
    family: 'gemini-text',
    enabled: true,
    route: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'chat', name: '普通对话', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    kind: 'agent',
    textRole: 'chat',
    family: 'gemini-text',
    enabled: true,
    route: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'chat', name: '普通对话', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'gemini-3.6-flash',
    name: 'Gemini 3.6 Flash',
    kind: 'agent',
    textRole: 'chat',
    family: 'gemini-text',
    enabled: true,
    route: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'chat', name: '普通对话', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'glm-5.3-flash',
    name: 'GLM 5.3 Flash',
    kind: 'agent',
    textRole: 'chat',
    family: 'glm-text',
    enabled: true,
    route: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'chat', name: '普通对话', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },
  {
    id: 'grok-4-1-auto',
    name: 'Grok 4.1 Auto',
    kind: 'agent',
    textRole: 'chat',
    family: 'grok-text',
    enabled: true,
    route: '/v1/chat/completions',
    contentType: 'json',
    ratios: [],
    resolutions: [],
    modes: [{ id: 'chat', name: '普通对话', enabled: true }],
    maxConcurrency: 1,
    maxCount: 1,
  },

  // —— Video ——
  {
    id: 'grok-video-3',
    name: 'Grok Video 3',
    kind: 'video',
    family: 'grok-video',
    enabled: true,
    route: '/v1/videos',
    queryRoute: '/v1/videos/{task_id}',
    contentType: 'multipart',
    ratios: GROK_RATIOS,
    resolutions: GROK_SIZES,
    durationRange: { min: 5, max: 10, step: 1 },
    modes: GROK_MODES,
    maxConcurrency: 2,
    maxCount: 4,
    referenceField: 'input_reference',
  },
  {
    id: 'grok-video-3-pro',
    name: 'Grok Video 3 Pro',
    kind: 'video',
    family: 'grok-video',
    enabled: true,
    route: '/v1/videos',
    queryRoute: '/v1/videos/{task_id}',
    contentType: 'multipart',
    ratios: GROK_RATIOS,
    resolutions: GROK_SIZES,
    fixedSeconds: 10,
    durations: [10],
    modes: GROK_MODES,
    maxConcurrency: 2,
    maxCount: 4,
    referenceField: 'input_reference',
  },
  {
    id: 'grok-video-3-max',
    name: 'Grok Video 3 Max',
    kind: 'video',
    family: 'grok-video',
    enabled: true,
    route: '/v1/videos',
    queryRoute: '/v1/videos/{task_id}',
    contentType: 'multipart',
    ratios: GROK_RATIOS,
    resolutions: GROK_SIZES,
    fixedSeconds: 15,
    durations: [15],
    modes: GROK_MODES,
    maxConcurrency: 2,
    maxCount: 4,
    referenceField: 'input_reference',
  },
  {
    id: 'MiniMax-H3',
    name: 'MiniMax H3',
    kind: 'video',
    family: 'minimax',
    enabled: true,
    // Legacy H3 route: /v1/videos; query: /v1/videos/{task_id}.
    route: '/v2/video_generation',
    queryRoute: '/v2/query/video_generation/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1', 'adaptive', '21:9', '4:3', '3:4'],
    resolutions: ['720P', '768P', '1080P', '2K'],
    durationRange: { min: 4, max: 15, step: 1 },
    durations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'i2v', name: '首帧生视频（跟随素材画幅）', enabled: true },
      { id: 'fl', name: '首尾帧（跟随素材画幅）', enabled: true },
      { id: 'ref', name: '多模态参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 4,
  },
  {
    id: 'omni-fast',
    name: 'Omni Fast',
    kind: 'video',
    family: 'omni',
    enabled: true,
    route: '/v1/videos',
    queryRoute: '/v1/videos/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1'],
    resolutions: ['720P', '1080P'],
    durationRange: { min: 4, max: 10, step: 1 },
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'i2v', name: '首帧生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 5,
    referenceField: 'images',
  },
  {
    id: 'omni-fast-v2v',
    name: 'Omni Fast 参考视频',
    kind: 'video',
    family: 'omni',
    enabled: true,
    route: '/v1/videos',
    queryRoute: '/v1/videos/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1'],
    resolutions: ['720P', '1080P'],
    durationRange: { min: 4, max: 10, step: 1 },
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'i2v', name: '首帧生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
      { id: 'v2v', name: '参考视频', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 5,
    referenceField: 'video',
  },
  {
    id: 'veo_3_1',
    name: 'Veo 3.1',
    kind: 'video',
    family: 'veo',
    enabled: true,
    route: '/v1/videos',
    queryRoute: '/v1/videos/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1'],
    resolutions: ['720P', '1080P'],
    durations: [5, 6, 7, 8],
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 4,
  },
  {
    id: 'veo_3_1-fast',
    name: 'Veo 3.1 Fast',
    kind: 'video',
    family: 'veo',
    enabled: true,
    route: '/v1/videos',
    queryRoute: '/v1/videos/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1'],
    resolutions: ['720P', '1080P'],
    durations: [5, 6, 7, 8],
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 4,
  },
  {
    id: 'doubao-seedance-2-0-260128',
    name: 'Seedance 2.0',
    kind: 'video',
    family: 'seedance',
    enabled: true,
    route: '/v1/video/generations',
    queryRoute: '/v1/video/generations/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1', '4:3', 'adaptive'],
    resolutions: ['480P', '720P', '1080P'],
    durationRange: { min: 4, max: 15, step: 1 },
    durations: [4,5,6,7,8,9,10,11,12,13,14,15,-1],
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'i2v', name: '首帧生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 4,
  },
  {
    id: 'doubao-seedance-2-0-fast-260128',
    name: 'Seedance 2.0 Fast',
    kind: 'video',
    family: 'seedance',
    enabled: true,
    route: '/v1/video/generations',
    queryRoute: '/v1/video/generations/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1', '4:3', 'adaptive'],
    resolutions: ['480P', '720P', '1080P'],
    durationRange: { min: 4, max: 15, step: 1 },
    durations: [4,5,6,7,8,9,10,11,12,13,14,15,-1],
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'i2v', name: '首帧生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 4,
  },
  {
    id: 'doubao-seedance-2.5',
    aliases: ['doubao-seedance-2-5'],
    name: 'Seedance 2.5',
    kind: 'video',
    family: 'seedance',
    enabled: true,
    route: '/v1/video/generations',
    queryRoute: '/v1/video/generations/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1', '4:3', 'adaptive'],
    resolutions: ['480P', '720P', '1080P'],
    // Video protocol and limits confirmed by user-supplied 4..txt.
    durationRange: { min: 4, max: 15, step: 1 },
    durations: [4,5,6,7,8,9,10,11,12,13,14,15,-1],
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'i2v', name: '首帧生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 4,
  },
  {
    id: 'doubao-seedance-2-0-mini',
    name: 'Seedance 2.0 Mini',
    kind: 'video',
    family: 'seedance',
    enabled: true,
    route: '/v1/video/generations',
    queryRoute: '/v1/video/generations/{task_id}',
    contentType: 'json',
    ratios: ['16:9', '9:16', '1:1', '4:3', 'adaptive'],
    resolutions: ['480P', '720P', '1080P'],
    durationRange: { min: 4, max: 15, step: 1 },
    durations: [4,5,6,7,8,9,10,11,12,13,14,15,-1],
    modes: [
      { id: 't2v', name: '文生视频', enabled: true },
      { id: 'i2v', name: '首帧生视频', enabled: true },
      { id: 'fl', name: '首尾帧', enabled: true },
      { id: 'ref', name: '全能参考', enabled: true },
    ],
    maxConcurrency: 2,
    maxCount: 4,
  },

  // —— Image ——
  {
    id: 'gpt-image-2',
    name: 'GPT Image 2',
    kind: 'image',
    family: 'gpt-image',
    enabled: true,
    route: '/v1/images/generations',
    contentType: 'json',
    ratios: IMAGE_RATIOS_STD,
    resolutions: ['1K', '2K'],
    modes: IMAGE_MODES,
    maxConcurrency: 4,
    maxCount: 8,
  },
  {
    id: 'grok-4-2-image',
    name: 'Grok 4.2 Image',
    kind: 'image',
    family: 'grok-image',
    enabled: true,
    route: '/v1/images/generations',
    contentType: 'json',
    ratios: IMAGE_RATIOS_STD,
    resolutions: ['1K', '2K'],
    modes: IMAGE_MODES,
    maxConcurrency: 4,
    maxCount: 8,
  },
  {
    id: 'doubao-seedream-5-0-260128',
    name: 'Seedream 5.0',
    kind: 'image',
    family: 'seedream',
    enabled: true,
    route: '/v1/images/generations',
    contentType: 'json',
    ratios: [...IMAGE_RATIOS_STD, '21:9'],
    resolutions: ['1K', '2K', '4K'],
    modes: IMAGE_MODES,
    maxConcurrency: 4,
    maxCount: 8,
  },
  {
    id: 'gemini-3-pro-image-preview',
    name: 'Gemini 3 Pro Image',
    kind: 'image',
    family: 'gemini-image',
    enabled: true,
    route: '/v1beta/models/gemini-3-pro-image-preview:generateContent',
    contentType: 'json',
    ratios: ['1:1', '16:9', '9:16'],
    resolutions: ['1K', '2K'],
    modes: IMAGE_MODES,
    maxConcurrency: 2,
    maxCount: 4,
  },
  {
    id: 'qwen-image-3.0',
    name: 'Qwen Image 3.0',
    kind: 'image',
    family: 'qwen-image',
    enabled: true,
    route: '/v1/images/generations',
    contentType: 'json',
    ratios: IMAGE_RATIOS_STD,
    resolutions: ['1K', '2K'],
    modes: IMAGE_MODES,
    maxConcurrency: 4,
    maxCount: 8,
  },
  {
    id: 'qwen-image-3.0-pro',
    name: 'Qwen Image 3.0 Pro',
    kind: 'image',
    family: 'qwen-image',
    enabled: true,
    route: '/v1/images/generations',
    contentType: 'json',
    ratios: IMAGE_RATIOS_STD,
    resolutions: ['1K', '2K'],
    modes: IMAGE_MODES,
    maxConcurrency: 4,
    maxCount: 8,
  },
];

export function getModels() {
  return MODELS.filter((m) => m.enabled !== false).map((m) => ({ ...m }));
}

export function getModel(id) {
  return MODELS.find((m) => (m.id === id || m.aliases?.includes(id))) || null;
}

export function catalogPayload() {
  return { models: getModels(), source: 'duoyuanx', updatedAt: 'studio56' };
}
